# Dockerfile for Nginx
FROM nginx:alpine

RUN apk add --no-cache gettext
# Copy Nginx configuration
COPY nginx.conf.template /etc/nginx/nginx.conf.template
COPY default.conf /etc/nginx/default.conf
COPY nginxWithProfile.conf /etc/nginx/nginxWithProfile.conf


# Copy application code to Nginx directory
COPY . /var/www

COPY nginx-entrypoint.sh /nginx-entrypoint.sh
RUN chmod +x /nginx-entrypoint.sh
# Expose port 80
EXPOSE 80

# Start Nginx
ENTRYPOINT ["/nginx-entrypoint.sh"]